name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3]
        laravel: [8.*]
        nova: [3.*]
        stability: [prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*
            nova-dusk-suite: dev-master
          # - laravel: 7.*
          #   testbench: 5.*
          #   nova-dusk-suite: 7.x-dev
        exclude:
          - laravel: 8.*
            nova: 3.0.*
          - php: 7.3
            nova: 3.0.*

    env:
      DB_DATABASE: nova_settings
      DB_USERNAME: root
      DB_PASSWORD: password

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Nova ${{ matrix.nova }} - ${{ matrix.stability }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_DATABASE: nova_settings
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, gd
          coverage: none

      - name: Install dependencies
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
          composer require "laravel/framework:${{ matrix.laravel }}" "laravel/nova:${{ matrix.nova }}" "orchestra/testbench:${{ matrix.testbench }}" "orchestra/testbench-dusk:${{ matrix.testbench }}" "laravel/nova-dusk-suite:${{ matrix.nova-dusk-suite }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Execute Dusk tests
        run: |
          pwd
          printenv | grep DB_
          composer run-script dusk:prepare
          composer run-script dusk:assets
          composer run-script dusk:test
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: tests/Browser/screenshots
          name: Dusk-screenshots
